Createdsidebar header social media
WalidAmmarAli/PortafolioProjectS pull request #1
Opened 2023-04-28 22:58 UTC by WalidAmmarAli

#WebResponsivedesigne
*Create the header component
*Create style.css file
*Create linter file

2023-04-28 23:45 UTC, braincee requested changes
Hello @WalidAmmarAli 👋 , I am @braincee your Code Reviewer

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/78104544/225492039-ed22bba9-481a-489f-ae04-74623970af20.gif)

HIGHLIGHTS
------

 - GitHub flow rightfully used ✅
 - Meaningful title and summary for PR ✅
 - Professional README.md file ✅
 - No linter errors ✅

REQUIRED CHANGES ♻️
------
**_Please check the comments under the review._**

OPTIONAL CHANGES

- [x] [OPTIONAL] Please I suggest making your commit messages imperative tenses. Example `Add...` instead of `Added...`. Please check this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to help document your repository in a professional way

--------
**_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @braincee in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

----

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 23:45 UTC, braincee commented on index.html
> +        <h2 class="logo">My logo</h2>
- [ ] Please I highly recommend creating a separate `div` tag for the "My Logo" and removing it from the `nav` tag placing it on the left. Kindly replace the `h2` tag with link `a` tag to implement HTML semantics and better user experience.  Please check this [link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more information. 😄

2023-04-28 23:45 UTC, braincee commented on index.html
> +    <main class="main">
- [ ] Please I highly recommend replacing the `main` tag with the `section` tag which wraps around the specific content to stand alone. Doing so implements HTML semantics and better user experience. Please check this [link](https://developer.mozilla.org/en-US/docs/Glossary/Semantics) form more information. 😄

2023-04-28 23:45 UTC, braincee commented on index.html
> +      </div>
- [ ] Please I suggest wrapping the social media icons with `ul` tags to group them and each icon `li` tags to implement HTML semantics and better user experience. 😄 

Example:

```
 <div class="socialMedia">
        <ul>
          <li><a href=""><img src="/Images/Vector (2).png" alt="" class="icon"></a></li>
          <li><a href=""><img src="/Images/Linkedin icon.png" alt="" class="icon"></a></li>
          <li><a href=""><img src="/Images/Vector (6).png" alt="" class="icon icon-3"></a></li>
          <li><a href=""><img src="/Images/Vector (4).png" alt="" class="icon"></a></li>
          <li><a href=""><img src="/Images/Vector (5).png" alt="" class="icon"></a></li>
        </ul>
      </div>
```

2023-04-28 23:45 UTC, braincee commented on index.html
> +    <header class="header">
- [ ] Please I suggest sticking to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0-1&t=wXOihw1H1KgFZBa6-0) template. 😄 

_**REQUIRED FIGMA DESIGN**_

![Screenshot (74)](https://user-images.githubusercontent.com/78104544/235269639-3a3a8374-aca3-40d8-b49a-d04d86f21b02.png)


_**YOUR DESIGN**_

- [ ] Please I highly recommend making changes to the `margin-top` property to fit the required figma design

![Screenshot (259)](https://user-images.githubusercontent.com/78104544/235269916-ce3a281a-2908-4d6f-b934-12af0acb3eb3.jpg)

2023-04-28 23:45 UTC, braincee commented on index.html
> +      <div class="socialMedia">
- [ ] Please I suggest sticking to the [figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0-1&t=wXOihw1H1KgFZBa6-0) template. 😄

_**REQUIRED FIGMA DESIGN**_

![Screenshot (75)](https://user-images.githubusercontent.com/78104544/235270123-deda30e1-bccc-4a74-8093-665618fd63d4.png)

_**YOUR DESIGN**_

- [ ] Please I suggest removing the outlines around the social media icons to fit the required figma design. 😄 

![Screenshot (260)](https://user-images.githubusercontent.com/78104544/235270151-4faba892-28c7-40ae-8300-8b427ddc76db.png)

2023-04-29 01:25 UTC, WalidAmmarAli commented
Hi @braincee would like to know if we can have a video zoom I have doubt

El vie, 28 abr 2023 a la(s) 17:46, Stephen Annor ***@***.***)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Hello @WalidAmmarAli <https://github.com/WalidAmmarAli> 👋 , I am
> @braincee <https://github.com/braincee> your Code Reviewer
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: so-close]
> <https://user-images.githubusercontent.com/78104544/225492039-ed22bba9-481a-489f-ae04-74623970af20.gif>
> HIGHLIGHTS
>
>    - GitHub flow rightfully used ✅
>    - Meaningful title and summary for PR ✅
>    - Professional README.md file ✅
>    - No linter errors ✅
>
> REQUIRED CHANGES ♻️
>
> *Please check the comments under the review.*
>
> OPTIONAL CHANGES
>
>    - [OPTIONAL] Please I suggest making your commit messages imperative
>    tenses. Example Add... instead of Added.... Please check this link
>    <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md>
>    to help document your repository in a professional way
>
> ------------------------------
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me @braincee <https://github.com/braincee> in
> your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/WalidAmmarAli/PortafolioProjectS/pull/1#discussion_r1180874170>
> :
>
> > +<!DOCTYPE html>
> +<html lang="en">
> +
> +<head>
> +  <meta charset="UTF-8">
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +  <link rel="stylesheet" href="style.css">
> +  <script src="https://kit.fontawesome.com/89d87f2112.js" crossorigin="anonymous"></script>
> +  <title>Portafolio</title>
> +</head>
> +<body>
> +    <header class="header">
> +      <div class="tallbar"></div>
> +      <nav class="navbar">
> +        <h2 class="logo">My logo</h2>
>
>
>    - Please I highly recommend creating a separate div tag for the "My
>    Logo" and removing it from the nav tag placing it on the left. Kindly
>    replace the h2 tag with link a tag to implement HTML semantics and
>    better user experience. Please check this link
>    <https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page>
>    for more information. 😄
>
> ------------------------------
>
> In index.html
> <https://github.com/WalidAmmarAli/PortafolioProjectS/pull/1#discussion_r1180875289>
> :
>
> > +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +  <link rel="stylesheet" href="style.css">
> +  <script src="https://kit.fontawesome.com/89d87f2112.js" crossorigin="anonymous"></script>
> +  <title>Portafolio</title>
> +</head>
> +<body>
> +    <header class="header">
> +      <div class="tallbar"></div>
> +      <nav class="navbar">
> +        <h2 class="logo">My logo</h2>
> +        <i class="fa-solid fa-bars"></i>
> +      </nav>
> +    </header>
> +
> +    <main class="main">
>
>
>    - Please I highly recommend replacing the main tag with the section
>    tag which wraps around the specific content to stand alone. Doing so
>    implements HTML semantics and better user experience. Please check this
>    link <https://developer.mozilla.org/en-US/docs/Glossary/Semantics>
>    form more information. 😄
>
> ------------------------------
>
> In index.html
> <https://github.com/WalidAmmarAli/PortafolioProjectS/pull/1#discussion_r1180878308>
> :
>
> > +      <div class="socialMedia">
> +        <a href=""><img src="/Images/Vector (2).png" alt="" class="icon"></a>
> +        <a href=""><img src="/Images/Linkedin icon.png" alt="" class="icon"></a>
> +        <a href=""><img src="/Images/Vector (6).png" alt="" class="icon icon-3"></a>
> +        <a href=""><img src="/Images/Vector (4).png" alt="" class="icon"></a>
> +        <a href=""><img src="/Images/Vector (5).png" alt="" class="icon"></a>
> +      </div>
>
>
>    - Please I suggest wrapping the social media icons with ul tags to
>    group them and each icon li tags to implement HTML semantics and
>    better user experience. 😄
>
> Example:
>
>  <div class="socialMedia">
>         <ul>
>           <li><a href=""><img src="/Images/Vector (2).png" alt="" class="icon"></a></li>
>           <li><a href=""><img src="/Images/Linkedin icon.png" alt="" class="icon"></a></li>
>           <li><a href=""><img src="/Images/Vector (6).png" alt="" class="icon icon-3"></a></li>
>           <li><a href=""><img src="/Images/Vector (4).png" alt="" class="icon"></a></li>
>           <li><a href=""><img src="/Images/Vector (5).png" alt="" class="icon"></a></li>
>         </ul>
>       </div>
>
> ------------------------------
>
> In index.html
> <https://github.com/WalidAmmarAli/PortafolioProjectS/pull/1#discussion_r1180882229>
> :
>
> > @@ -0,0 +1,51 @@
> +<!DOCTYPE html>
> +<html lang="en">
> +
> +<head>
> +  <meta charset="UTF-8">
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
> +  <link rel="stylesheet" href="style.css">
> +  <script src="https://kit.fontawesome.com/89d87f2112.js" crossorigin="anonymous"></script>
> +  <title>Portafolio</title>
> +</head>
> +<body>
> +    <header class="header">
>
>
>    - Please I suggest sticking to the figma design
>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0-1&t=wXOihw1H1KgFZBa6-0>
>    template. 😄
>
> *REQUIRED FIGMA DESIGN*
>
> [image: Screenshot (74)]
> <https://user-images.githubusercontent.com/78104544/235269639-3a3a8374-aca3-40d8-b49a-d04d86f21b02.png>
>
> *YOUR DESIGN*
>
>    - Please I highly recommend making changes to the margin-top property
>    to fit the required figma design
>
> [image: Screenshot (259)]
> <https://user-images.githubusercontent.com/78104544/235269916-ce3a281a-2908-4d6f-b934-12af0acb3eb3.jpg>
> ------------------------------
>
> In index.html
> <https://github.com/WalidAmmarAli/PortafolioProjectS/pull/1#discussion_r1180883441>
> :
>
> > +    </header>
> +
> +    <main class="main">
> +      <div class="title">
> +        <h1>I’m Ammar.
> +          Glad to see you!</h1>
> +      </div>
> +      <div class="parrafo">
> +        <p>I’m a software developer! I can help you build a product , feature or website Look through some of my work
> +          and experience! If you like what you see and have a project you need coded, don’t hesitate to contact me.
> +        </p>
> +      </div>
> +      <div class="connect">
> +        <img src="/Images/LET’S CONNECT.png" alt="" >
> +      </div>
> +      <div class="socialMedia">
>
>
>    - Please I suggest sticking to the figma design
>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0-1&t=wXOihw1H1KgFZBa6-0>
>    template. 😄
>
> *REQUIRED FIGMA DESIGN*
>
> [image: Screenshot (75)]
> <https:/ [...]

2023-04-29 03:17 UTC, TadesseDev requested changes
### Hi @WalidAmmarAli 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 03:17 UTC, TadesseDev commented on index.html
> +    </section>
- [ ] Good job making the changes as requested by the previous reviewer, But following your changes your social media icons are not visible on the webpage. I suspect this is because of how you address your icons. adding the relative path to your address seems to fix the issue. Please use src="./Images/Vector (2).png" instead of src="/Images/Vector (2).png" and see if it works.
![image](https://user-images.githubusercontent.com/69077061/235280807-66b2f0cd-625f-4b7d-b282-756c5896ca85.png)

2023-04-29 03:17 UTC, TadesseDev commented on index.html
> +            <h1>I’m Ammar.
- [ ] Dear @WalidAmmarAli, as suggested by the previous reviewer, we need to stick to the figma design. And if you look closely at your design seems to have a lot of padding from the top which pushes your content all the way down. Please take a look at that. 
- [Potional] Also, the background image is not exactly how it looks on the figma design, I strongly suggest making the appropriate changes to update it. 
### Your design 
![image](https://user-images.githubusercontent.com/69077061/235281007-7354c248-a6c6-4153-9cf9-074bde881a83.png)

### Figma design 
![image](https://user-images.githubusercontent.com/69077061/235281040-277edffa-9c5a-4344-9b57-42a497c255f2.png)

2023-04-29 18:33 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @WalidAmmarAli, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewers. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title and summary. ✔️  
- Portfolio: setup and mobile first ✔️  
- Follow the Figma Design Template ✔️  
- Touchable mobile screen size of `375px` ✔️  
- Good use of Github flow ✔️ 

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 18:33 UTC, brainconnect93 commented on README.md
> +To run tests, run the following command:
- [ ] [OPTIONAL] I would kindly suggest, You give some line of code user's visiting your page can run to get the project running. You haven't stated any code here and user might fine it difficult to run your project. I actually marked it optional because other reviewers did not mention it.

2023-04-29 18:41 UTC, WalidAmmarAli commented
Responsive Desing 1.1

2023-04-29 18:43 UTC, merged