create the second section of the page
WalidAmmarAli/PortafolioProjectS pull request #2
Opened 2023-04-30 01:24 UTC by WalidAmmarAli

#ResponsiveDesign.

*Create the project section. 
*Create the languages section. 
*Creatabout myself section.
*Add style to this section.

2023-04-30 02:30 UTC, Efiamotu-1 requested changes
Hi @WalidAmmarAli , 

![](https://camo.githubusercontent.com/9394efa3662ade294180d682ebade56334efde7f9b0ffaf2da4786d70e86ee0c/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e6769663f6369643d65636630356534376b357561706470746730306e69646277337161787838697167737573676173776369326333756831267269643d67697068792e6769662663743d67)

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-30 02:30 UTC, Efiamotu-1 commented on index.html
> +                        </a></li>
- [ ] your design currently has some issues with the line heigh and spacing for each projects title and paragraph. please take a look at the figma template and use the provided css styling to achieve the required portfolio template. :+1: 
-figma design
![f-s-c](https://user-images.githubusercontent.com/89055502/235332024-ab24acb2-26ba-4c89-9e97-2192148c995e.png)
- your design
![s-15](https://user-images.githubusercontent.com/89055502/235332069-97a6a39d-1624-4b63-90e0-d9d6aaf67e40.png)

2023-04-30 02:30 UTC, Efiamotu-1 commented on index.html
> +                </div>
- [ ] your design for the technology is not the same as the figma template please go over the styling for the font's and fix it accordingly before making your next review request :+1: 
- figma design
![f-j-j](https://user-images.githubusercontent.com/89055502/235332099-f80578b5-d275-4f96-831c-7f817a3f1a89.png)
- your design
![s-j-j](https://user-images.githubusercontent.com/89055502/235332107-60ee4812-86ce-4e06-baff-2c57ece681aa.png)

2023-04-30 02:30 UTC, Efiamotu-1 commented on style.css
> +  }
- [ ] all of the contents of the about container is to be positioned using the flex property. this will come in handy when you start building the section for the desktop site :+1:

2023-04-30 02:30 UTC, Efiamotu-1 commented on index.html
> +                <h1 class="title-2">About Myself</h1>
- [ ] please make us of other heading tags such as `<h2>, <h3>` etc to display the `about myself`, you are expected to have only one h1 tag for screen readers and this is the html standard. :+1:

2023-04-30 02:30 UTC, Efiamotu-1 commented on index.html
- [ ] you have not implemented the button interaction which is a requirement for this milestone as seen in the image below
![req-btn-int](https://user-images.githubusercontent.com/89055502/235330062-99c93858-2749-4a80-ad0f-88815a4956e1.png)


> - i will provide you with possible steps to achieving this
- first off you need to give every button a unique class name eg `btn` and then style this btn class using pseudo selctors such as `:hover. :active` and apply the various background color and color from the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=39-122&t=bLjL2tJJSSkEfkRj-0) to these styling.
- so this is what your css code would look like
```
.btn:hover {
  background-color: red;
  color: white
}
```
- [ ] Note the example below is only for hover and i have only used random color do  well to check the figma for the correct color as shown below
![btn-t-1-int](https://user-images.githubusercontent.com/89055502/235332372-26ebeba7-6855-4677-a292-cfa3bb1a48e4.png)

2023-04-30 02:30 UTC, Efiamotu-1 commented on index.html
- [ ] please reduce the margin before the about me text. see the figma template below for guidance :+1: 
- figma design
![f-m](https://user-images.githubusercontent.com/89055502/235332445-e5558453-c47b-4dae-9eed-d199ae3d9935.png)
- your design
![s-m](https://user-images.githubusercontent.com/89055502/235332455-8d876f29-15cc-48b4-bb97-e94a299bfd82.png)

2023-04-30 02:30 UTC, Efiamotu-1 commented on index.html
- [ ] please work on the design as shown below your text and icon is not the same as in the figma template :+1: 
- figma design
![f-fra](https://user-images.githubusercontent.com/89055502/235332543-215a308d-bd53-4528-8f1a-1ad3d611d9c3.png)
- your design
![s-fra](https://user-images.githubusercontent.com/89055502/235332549-74af1c50-cc7d-4931-b31b-fea27ffec0e7.png)

2023-04-30 02:30 UTC, Efiamotu-1 commented on index.html
- [ ] your web page curently has margin to the right which is causing there to be an overlow on a mobile screen as seen in the image below please make sure to correct this when making your next review request :+1: 
![margin](https://user-images.githubusercontent.com/89055502/235332622-7d8ae157-1134-4d55-9603-4ecc2363de9a.png)

2023-04-30 02:30 UTC, Efiamotu-1 commented on style.css
[OPTIONAL]
- [ ] your css styling in line 14 adding a `posititon: fixed` to the header is currently causing some distorting to the web page when user scrolls kindly remove it as it is currently not a requirement of this milestone but it is affecting your projects design :+1:

2023-05-02 20:06 UTC, Shedrack-Sunday requested changes
Hello @WalidAmmarAli      👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing some of the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights 
- Right file structure used✔️  
- Moderate UI design  ✔️  
  
# Required Changes  🌵 

- [ ] There are a few things you need to take note of to have a great project as expected 👍 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-02 20:06 UTC, Shedrack-Sunday commented on index.html
> +                    <h1 class="title-2">About Myself</h1>
- [ ] The reason for having only one `h1` tag in a project is to maintain proper document structure and hierarchical order. The `h1` tag is the most important heading element in HTML and represents the main heading of a page or section. Having multiple `h1` tags can cause confusion in search engine optimization (SEO) and accessibility, as well as make it difficult for screen readers to understand the main content of the page. 

- [ ] It is recommended to use only one `h1` tag per page and use other heading tags (h2, h3, etc.) to create a clear and structured document outline. In this case, this is your second `h1`, since the header above has one

2023-05-02 20:06 UTC, Shedrack-Sunday commented on index.html
> +                    <div class="lenguaje1">
- [ ] For your technology categories ("Languages", "Frameworks" and "Skills") kindly use a `ul`, each of them in a `li` tag.
- The technology in each category(e.g., "JavasScript", "HTML" and "CSS") should  also be a list `ul` and each of them a `li`.
- Creating s list the way i suggested is the semantically best way to go about it, and i advice you stick it it going forward, as you become a better developer 👍

2023-05-03 16:41 UTC, usorfaitheloho approved these changes
Hi @WalidAmmarAli  , 
# STATUS: APPROVED! 🥇 💯 
- [x] Nice Design, Keep it up!!
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 17:06 UTC, merged