Desktop design branch
WalidAmmarAli/PortafolioProjectS pull request #4
Opened 2023-05-13 23:16 UTC by WalidAmmarAli

#Create-desktop-design
*Create the html file.
*Create the css style
*Use linter to solve errors
*Add animation and transition effects.

2023-05-13 23:51 UTC, OyePriscilla requested changes
Hi @WalidAmmarAli 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Use CSS media queries to make desktop version ✔️ 
App responsive ✔️ 

## Required Changes ♻️

- [ ] For your README file to be more engaging and informative, kindly ensure the the link in show your support section is directing visitors appropriately (maybe to your [issues](https://github.com/WalidAmmarAli/PortafolioProjectS/issues) page). Currently, I was redirected to your repo. ℹ️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-13 23:51 UTC, OyePriscilla commented on index.html
>          <p class="title-informations ">
- [ ] Please kindly add background-image to this element in accordance to the given design, this will improve the outlook of your app. 👍 

## Your Design
<img width="923" alt="Untitled" src="https://github.com/WalidAmmarAli/PortafolioProjectS/assets/103386183/c995eb30-a653-44d2-9763-abb9680c9436">

## Figma Design
<img width="516" alt="Untitled" src="https://github.com/WalidAmmarAli/PortafolioProjectS/assets/103386183/655181a2-18b1-442c-9d1f-fb15f2428437">

2023-05-13 23:51 UTC, OyePriscilla commented on style.css
> +  }
- [ ] Kindly add border-radius (right) to this section according to the given template. ℹ️ 

## Figma Design

<img width="528" alt="Untitled" src="https://github.com/WalidAmmarAli/PortafolioProjectS/assets/103386183/51c7b5a0-b9f5-4cd1-aabc-95c405dd26e7">

2023-05-13 23:51 UTC, OyePriscilla commented on style.css
> +  }
- [ ] Kindly increase the spacing of all the cards element according to the given template. 👍 

## Figma Design

<img width="541" alt="Untitled" src="https://github.com/WalidAmmarAli/PortafolioProjectS/assets/103386183/a9ba5d9c-1541-415d-bb89-9ba411a1f6de">

## Your Design
<img width="949" alt="Untitled" src="https://github.com/WalidAmmarAli/PortafolioProjectS/assets/103386183/c0e7cd2d-0b33-4cb8-a416-e51fa687a144">

2023-05-14 00:42 UTC, Efiamotu-1 approved these changes
Hi @WalidAmmarAli, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions

- The previous reviewer requested for the change below please kindly implement it before merging, use the link which was provided as it will take you to your issues page :+1: 
- [ ] For your README file to be more engaging and informative, kindly ensure the the link in show your support section is directing visitors appropriately (maybe to your [issues](https://github.com/WalidAmmarAli/PortafolioProjectS/issues) page). Currently, I was redirected to your repo. information_source

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-14 00:59 UTC, merged